idmc-labs/idmc-website-components

- .github/workflows/ci.yml
- aws/cloudformation.yaml
- Add cloudformation stack data.
Branch `release` will be released to AWS.
> Update gh for aws deployment.

- app/components/Tabs/TabContext.tsx
- app/components/Tabs/index.tsx
- app/views/CountryProfile/index.tsx
- app/views/GoodPractice/index.tsx
- Addresses XXX
- Depends on XXX
* Detailed list or prose of changes
* Breaking changes
* Changes to configurations
> Add unique to country and region

- app/components/Carousel/CarouselItem/styles.css
> add z-index to carousel item

- .github/workflows/ci.yml
- app/Base/configs/apollo.ts
- app/components/DisplacementIcon/index.tsx
- app/views/CountryProfile/index.tsx
- schema.graphql
> Update disaster icon map

- app/views/CountryProfile/index.tsx
> Add client id on country profile

- .babelrc
- app/Base/configs/apollo.ts
- app/Base/configs/lang.ts
- app/Base/index.tsx
- app/components/GoodPracticeItem/index.tsx
- app/components/LanguageSelectInput/index.tsx
- app/components/LanguageSelectInput/styles.css
- app/components/Message/index.tsx
- app/context/LanguageContext.ts
- app/hooks/useLocalStorage.ts
- app/hooks/useTranslation.ts
- app/utils/strings.tsx
- app/views/GoodPractice/index.tsx
- app/views/GoodPractice/styles.css
- app/views/GoodPractices/index.tsx
- app/views/GoodPractices/styles.css
- tsconfig.json
* Add french translation to static content
> Add static translations to good practices

- app/views/GoodPractices/index.tsx
- app/views/GoodPractices/styles.css
- Addresses #15 #16
* Add pagination in good practices listing page
* Remove ellipsized content from FAQs
> Add pagination for good practices listing page

- app/Base/styles.css
- app/views/CountryProfile/index.tsx
- app/views/CountryProfile/styles.css
* Change header image position
* Remove read more from header
> Add country profile fixes

- app/views/CountryProfile/index.tsx
* Replace pager in related materials from show-more to pagination
> Replace pager in related materials from show-more to pagination

- app/views/CountryProfile/index.tsx
- app/views/GoodPractices/index.tsx
- app/views/GoodPractices/styles.css
- Addresses 
- #33
- #34 
* Remove the 'Submit a new good practice' button from Good Practices
* Remove Figures Analysis section from Country Profile
> Remove Figures Analysis section from Country Profile

- app/Base/index.tsx
- app/components/IduMap/RawIduMap/index.tsx
- app/components/IduMap/useIduMap.tsx
- app/utils/common.ts
- app/views/CountryProfile/index.tsx
- Pass iso3 on country profile useIduMap
- Remove downloads from IDU Map
- Add links to IDU Map
> Fix filters from IDU Map

- app/components/IduMap/useIduMap.tsx
> Only show last 6 months on slider for IDU

- app/components/IduMap/useIduMap.tsx
- app/views/CountryProfile/index.tsx
> Change button label to GIDD

- app/Base/configs/lang.ts
- app/views/GoodPractice/index.tsx
- app/views/GoodPractices/index.tsx
- app/views/GoodPractices/styles.css
* Unhide the 'add new good practice' modal
> Unhide 'add new good practices'

- Dockerfile
- app/Base/configs/lang.ts
- app/components/TinyMceEditorInput/index.tsx
- app/components/TinyMceEditorInput/styles.css
- app/views/GoodPractices/AddGoodPractice/index.tsx
- app/views/GoodPractices/AddGoodPractice/styles.css
- Task: https://github.com/idmc-labs/idmc-website-components/issues/42
- Rename good practice form labels as mentioned
> Add changes to fields of good practice modal form

- app/Base/configs/lang.ts
- app/components/TinyMceEditorInput/index.tsx
- app/views/GoodPractices/AddGoodPractice/index.tsx
- app/views/GoodPractices/AddGoodPractice/styles.css
- Issue: https://github.com/idmc-labs/idmc-website-components/issues/49#issue-1612718208
- Issue: https://github.com/idmc-labs/idmc-website-components/issues/48#issue-1612715625
- Issue: https://github.com/idmc-labs/idmc-website-components/issues/50#issue-1612718795
- Server branch: https://github.com/idmc-labs/gidd-server/pull/28#issue-1606146367
- Add logic to show label names in french when choosen to submit in french
- Add changes to ongoing checkbox
> Add updates to good practice form modal

- app/views/GoodPractices/AddGoodPractice/index.tsx
- app/views/GoodPractices/AddGoodPractice/styles.css
> Fix popup issue

- app/Base/index.tsx
- app/components/IduMap/styles.css
- app/utils/common.ts
- app/views/ConflictWidget/index.tsx
- app/views/ConflictWidget/styles.css
- app/views/CountryProfile/index.tsx
- app/views/CountryProfile/styles.css
- app/views/DisasterWidget/index.tsx
- app/views/DisasterWidget/styles.css
- app/views/GoodPractices/index.tsx
- app/views/Home/index.tsx
- app/views/Home/styles.css
- app/views/IduWidget/index.tsx
- app/views/IduWidget/styles.css
- app/views/Template/styles.css
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/651#issue-1633255844
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/650#issue-1633255591
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/649#issue-1633255157
- Added conflict widget as widget 1
- Added disaster widget as widget 2
- Added InternalDisplacement widget as widget 3
> Addition of multiple widgets for conflict and disaster

- app/Base/styles.css
- app/components/CollapsibleContent/index.tsx
- app/components/Container/index.tsx
- app/components/FigureAnalysis/index.tsx
- app/components/FigureAnalysis/styles.css
- app/components/GridFilterInputContainer/styles.css
- app/components/NumberBlock/styles.css
- app/index.html
- app/views/ConflictWidget/index.tsx
- app/views/Gidd/DataTable/index.tsx
- app/views/Gidd/DataTable/styles.css
- app/views/Gidd/EventsTable/index.tsx
- app/views/Gidd/index.tsx
- app/views/Gidd/styles.css
* Fix filters in data table
* Separate data/event tables in tabs
* Use switch to switch between different modes in charts
* Make page responsive
> Fix UI/UX issues

- app/components/DisplacementIcon/index.tsx
- app/components/Header/index.tsx
- app/components/Heading/index.tsx
- app/components/Heading/styles.css
- app/components/Tabs/TabList/index.tsx
- app/components/Tabs/TabList/styles.css
- app/utils/common.ts
- app/views/ConflictWidget/index.tsx
- app/views/DisasterWidget/index.tsx
- app/views/Gidd/DataTable/index.tsx
- app/views/Gidd/EventsTable/index.tsx
- app/views/Gidd/index.tsx
- app/views/Gidd/styles.css
- app/views/IduWidget/index.tsx
> Differentiate between two "Mass Movement" options

- app/views/Gidd/index.tsx
* Use combined stats API for countries and total data
Depends on: https://github.com/idmc-labs/helix-server/pull/479/files
> Use combined stats

- app/views/ConflictWidget/index.tsx
- app/views/CountryProfile/FigureAnalysis/index.tsx
- app/views/CountryProfile/data.ts
- app/views/Gidd/index.tsx
> Rename "Total Number of IDPs"

- app/views/Gidd/DataTable/index.tsx
- app/views/Gidd/index.tsx
Depends on https://github.com/idmc-labs/helix-server/pull/486
> Filter displacement table by cause

- app/Base/configs/lang.ts
- app/components/TinyMceEditorInput/index.tsx
> Update text limit

- app/views/ConflictWidget/index.tsx
- app/views/DisasterWidget/index.tsx
- app/views/Gidd/index.tsx
> Fix issue with double slash on url

- .github/workflows/ci.yml
* Fix env for country profiles
> Fix env for country profiles

- .github/workflows/ci.yml
> Fix api end point in CI

- app/components/IduMap/useIduMap.tsx
- app/views/ConflictWidget/index.tsx
- app/views/DisasterWidget/index.tsx
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/849#issue-1754647742
- Change the button name "Go to our Data Centre (GIDD)" to "Go to IDMC's database"
> Rename the button name to IDMC database

- app/Base/Page/index.tsx
- app/views/ConflictWidget/index.tsx
- app/views/DisasterWidget/index.tsx
- app/views/Gidd/DataTable/index.tsx
- app/views/Gidd/EventTitle/Modal/index.tsx
- app/views/Gidd/EventsTable/index.tsx
- app/views/Gidd/index.tsx
- issue: https://github.com/idmc-labs/helix2.0-meta/issues/787
- Server branch: https://github.com/idmc-labs/helix-server/pull/493#issue-1735771174
- Add changes made to the queries relative to GIDD
- Fix lint and typecheck issues
> Add new queries for gidd

- app/Base/Page/index.tsx
- app/Base/Page/styles.css
> Fix passing client code to standalone application

- app/Base/Page/index.tsx
> Fix styling for error messages

- app/Base/Page/index.tsx
- app/Base/index.tsx
- app/Base/styles.css
- app/views/Home/index.tsx
- package.json
- User should explicitly pass client_id
> Remove default client id

- app/Base/index.tsx
> Read id from query instead of window even in standalone mode

- .dockerignore
- .github/workflows/ci.yml
- Addresses middle helix-staging deployment for preview
- Remove docker from gh action
> Add temporary helix-staging preview deployment

- app/Base/configs/lang.ts
- app/components/TinyMceEditorInput/index.tsx
- app/views/GoodPractices/AddGoodPractice/index.tsx
- https://github.com/idmc-labs/idmc-website-components/issues/97
- https://github.com/idmc-labs/gidd-server/pull/39
- Fix `TinyMceEditorComponent` text limit condition
- Remove character limit of project description Good Practice form
> Remove and fix character limit in Good Practice

- app/components/FigureAnalysis/index.tsx
- app/components/IduMap/RawIduMap/index.tsx
- app/components/IduMap/RawIduMap/styles.css
- app/views/Gidd/DataTable/index.tsx
- app/views/Gidd/EventTitle/Modal/index.tsx
- app/views/Gidd/EventsTable/index.tsx
- https://github.com/idmc-labs/helix-server/pull/550
- Use eventCode instead of glideNumbers
> Use updated filters for gidd events

- .github/actions/run_build/action.yml
- .github/workflows/aws_deploy.yml
- .github/workflows/ci.yml
Addresses 
- Define local re-usable workflows/actions
- Use IAM anywhere role instead of access keys <https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/>
> Refactor CI/CD

- .github/actions/run_build/action.yml
- .github/workflows/ci.yml
- Addresses idmc website deployment by Axelerant
* Use new api endpoint for drupal
> Use new api endpoint for drupal

- app/views/CountryProfile/index.tsx
- https://github.com/idmc-labs/idmc-website-components/issues/105
- Update content type mapping in country profile
> Update content type mapping in country profile

- app/components/tableHelpers/index.tsx
- app/views/Gidd/index.tsx
- Sort hazard options
- Fix small table issue
> Add stretchable table

- app/components/tableHelpers/index.tsx
- app/views/Gidd/DataTable/index.tsx
- app/views/Gidd/EventsTable/index.tsx
- app/views/Gidd/EventsTable/styles.css
- app/views/Gidd/index.tsx
* Set width for columns
* Remove link to request access
> Remove link to request access

- app/utils/common.ts
- app/views/Gidd/EventTitle/Modal/index.tsx
- app/views/Gidd/EventsTable/index.tsx
- app/views/Gidd/index.tsx
- https://github.com/idmc-labs/helix-server/pull/631
- https://github.com/idmc-labs/helix2.0-meta/issues/1175
- https://github.com/idmc-labs/helix2.0-meta/issues/995
* Add filter value on export link query
* Remove glide number in GIDD events table
> Fix filter value on gidd export
